1. Porque no esta declarada la excepcion. Y hace falta declararla con throws en el método creaFicheroTempConCar.

2. En el método main, al final del try tenemos que poner ft.delete() sino lo ponemos no borraria el fichero.

3. 

